# Generated by Django 6.0.4 on 2026-04-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renderjob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
