# Generated by Django 6.0.4 on 2026-04-21 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle_type', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('side', 'Side')], max_length=10)),
                ('base_image', models.ImageField(upload_to='base_products/')),
                ('print_x', models.IntegerField(default=0, help_text='X coordinate of print area')),
                ('print_y', models.IntegerField(default=0, help_text='Y coordinate of print area')),
                ('print_width', models.IntegerField(default=200, help_text='Width of print area')),
                ('print_height', models.IntegerField(default=200, help_text='Height of print area')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
            ],
        ),
    ]
